name: Merge
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/merge-upstream@v1
        with:
          upstream: web2py/yatl
