name: Merge
on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:
jobs:
  merge:
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-action@v1
      - env:
          INPUTS_REPOSITORY: web2py/yatl
        uses: rekgrpth/git-fetch-upstream-merge-upstream-push-action@v1
